name: OWASP ZAP

permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Dependencies
        run: |
          cd project
          npm install
          npm run install:components

      - name: App
        run: |
          cd project
          npm run dev &
          sleep 15

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://localhost:3000'
          allow_issue_writing: false
          fail_action: false
          artifact_name: 'report'

      - name: Report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.html
